name: Compile Sketch

# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32-bluepad32:esp32:esp32  
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
            - name: esp32-bluepad32:esp32
              source-url: https://github.com/ricardoquesada/bluepad32.git
          sketch-paths: |
            - ./MiniSkidi_3.0/MiniSkidi_3.0.ino
          libraries: |
            - name: ESP32Servo
