name: Compile Sketch

# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      # - run: arduino-cli core update-index
      #   name: update Arduino CLI index
      - run: arduino-cli core install --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json esp32:esp32
        name: Install ESP32 core
      - run: arduino-cli core update-index
        name: update Arduino CLI index.. again
      - run: arduino-cli core install --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json,https://raw.githubusercontent.com/ricardoquesada/esp32-arduino-lib-builder/master/bluepad32_files/package_esp32_bluepad32_index.json esp32-bluepad32:esp32
        name: Install ESP32 Bluepad32 core
      - run: arduino-cli lib install ESP32Servo
        name: Install ESP32Servo library
      - run: arduino-cli compile --fqbn esp32-bluepad32:esp32:esp32 ./MiniSkidi_3.0/MiniSkidi_3.0.ino --output-dir ./MiniSkidi_3.0/build
        name: Compile sketch
      - name: 'Upload Build Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: compiled-artifacts
          path: ./MiniSkidi_3.0/build
          retention-days: 5
    
